version: '3.8'

services:
  # Banco de dados PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: ponto-postgres-prod
    environment:
      POSTGRES_DB: ponto
      POSTGRES_USER: ponto_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migration_8_16_8_17.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ponto-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ponto_user -d ponto"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # Redis para cache e sessões
  redis:
    image: redis:7-alpine
    container_name: ponto-redis-prod
    volumes:
      - redis_data:/data
    networks:
      - ponto-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # Aplicação Next.js
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ponto-app-prod
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://ponto_user:${POSTGRES_PASSWORD}@postgres:5432/ponto
      - REDIS_URL=redis://redis:6379
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - ponto-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: ponto-nginx-prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - app
    networks:
      - ponto-network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  ponto-network:
    driver: bridge 